export { Hero } from "./Hero";
export { CinematicHero } from "./CinematicHero";
export { ActorPageProvider, useActorPage } from "./ActorPageContext";
export { SocialBar } from "./SocialBar";
export { TrailerSection } from "./TrailerSection";
export { AboutSection } from "./AboutSection";
export { FilmographySlider } from "./FilmographySlider";
export { ClipsGallery } from "./ClipsGallery";
export { GeneratedClipsGallery } from "./GeneratedClipsGallery";
export { YouTubeReelsPlayer } from "./YouTubeReelsPlayer";
export { FanEmailModal } from "./FanEmailModal";
export { ContactSection } from "./ContactSection";
export { Footer } from "./Footer";
export { TabNavigation, type TabKey } from "./TabNavigation";
export { CommentsSection } from "./CommentsSection";
export { CommentCard } from "./CommentCard";
export { CommentEmailModal } from "./CommentEmailModal";
export { CareerHighlights } from "./CareerHighlights";
export { QuickStats } from "./QuickStats";
export { NotableProjectsCircular } from "./NotableProjectsCircular";
export { ActingPhilosophy } from "./ActingPhilosophy";
export { DirectBookingForm } from "./DirectBookingForm";
export { FollowTheJourney } from "./FollowTheJourney";
